version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    container_name: xinyesdkdemo-web-vue-app
    restart: unless-stopped
